launch: #起動パラメータ
  ros__parameters:
    slcan: false
    scan: false
    tcp_endpoint: true
    trajectory_planner: true

/**:  #ワイルドカード(ここのパラメータは全ノードから読める: <名前に注意>)
  ros__parameters:
    initial_pose: [-5.45, 0.3, 0.0]  #初期位置[x,y,yaw]
    2nd_initial_pose: [-5.45, 0.3, 0.0] #2つ目の初期位置[x,y,yaw]

    # 自動の並進  速度[m/s],加速度[m/s^2],加減速度[-m/s^2],躍度[m/s^3]
    linear_max_vel: 2.0
    linear_max_acc: 1.0
    linear_max_dec: 1.0
    linear_max_jer: 0.0
    # 回転  速度[deg/s],加速度[deg/s^2],加減速度[-deg/s^2],躍度[deg/s^3]
    angular_max_vel: 45.0
    angular_max_acc: 180.0
    angular_max_dec: 180.0
    angular_max_jer: 0.0

    canid:
      inject: 0x200
      injectable: 0x201
      movable: 0x202
      main_digital_button: 0x220
      sub_digital_button: 0x221

    port:
      robot_state: 57000
      pole_state: 61000
      joy_main: 50000
      joy_sub: 51000
      start_flag: 54000

controller_interface_node:
  ros__parameters:
    # 手動の並進　速度[m/s],加速度[m/s^2],加減速度[-m/s^2]
    linear_max_vel: 2.0
    linear_max_acc: 6.0
    linear_max_dec: 6.0
    # 手動の回転  速度[deg/s],加速度[deg/s^2],加減速度[-deg/s^2]
    angular_max_vel: 45.0
    angular_max_acc: 180.0
    angular_max_dec: 180.0
    #手動の上物　速度[deg/s],加速度[deg/s^2],加減速度[-deg/s^2] RC23−ERのdevelopブランチの348行目を参考
    injection_max_vel: 72.0
    injection_max_acc: 40.0
    injection_max_dec: 40.0

    heartbeat_ms: 100 #ハートビート周期[ms]
    convergence_ms: 100 #収束周期[ms]

    move_injection_heteronomy_ms: 17 #上物と足回り手動の周期[ms]

    udp_timeout_ms: 20 #UDPのタイムアウト値[ms]
    interval_ms: 50
    pole_ms: 20
    start_flag_ms: 100

    #erのcontroller_interfaceのcontroller_itnerfaceにpole情報を送るUDPのポート番号。また、受け取る番号
    udp_port_pole_execution: 53000 
    
    udp_port_state_num_er: 57000 #
    udp_port_state_num_rr: 60000 #
    udp_port_pole: 61000 #
    
    #リスタート、緊急、足回りの手自動、上物の手自動、手動の射角
    defalt_restart_flag: false
    defalt_emergency_flag: true
    defalt_move_autonomous_flag: true
    defalt_injection_autonomous_flag: true
    defalt_injection_mec: 1
    defalt_pitch: 45.0

    #収束の初期値
    defalt_spline_convergence: false
    defalt_injection_calculator0_convergence: false
    defalt_injection_calculator1_convergence: false
    defalt_injection0_convergence: false
    defalt_injection1_convergence: false


sequencer_node:
  ros__parameters:
    interval_ms: 50

spline_pid_node:
  ros__parameters:
    interval_ms: 20     #サイクル周期[ms]
    curvature_attenuation_rate: 0.0 #曲率の速度の減衰>=0 (0だと減衰なし)
    linear_planner_vel_limit_gain: 0.6  #速度計画機の速度上限値にかけるゲイン

    linear_planner_gain: 0.1 #並進速度計画機ゲイン  1.3
    linear_pos_gain: 3.0  #並進位置ズレのゲイン 3.5
    linear_pos_diff_gain: 0.1
    linear_pos_integral_gain: 0.01  #並進位置ズレの積分ゲイン

    angular_planner_gain: 1.7 #回転速度計画機ゲイン
    angular_pos_gain: 2.3 #回転位置ズレのゲイン
    angular_pos_integral_gain: 0.03  #回転位置ズレの積分ゲイン 0.01

    linear_pos_tolerance: 0.03  #並進到達位置の許容誤差[m]
    angular_pos_tolerance: 2.0  #回転到達位置の許容誤差[deg]

spline_trajectories_node:
  ros__parameters:
    resolution: 0.01  #起動点の分解能[m]


mcl_2d_node:
  ros__parameters:
    num_of_particle: 50     #粒子数
    odom_convariance:
      param1: 0.0   #回転成分から生まれる回転成分のズレ
      param2: 0.0   #並進成分から生まれる回転成分のズレ
      param3: 0.0   #並進成分から生まれる並進成分のズレ
      param4: 0.0   #回転成分から生まれる並進成分のズレ
      param5: 0.01   #Xのズレ
      param6: 0.01   #Yのズレ
    tf_laser2robot: [0.4655,0.0,0.0,  3.14159,0.0,0.0]  #ロボット->lidarのTF[x,y,z,r,p,y]


injection_param_calculator_node:
  ros__parameters:
    gravitational_accelerastion: 9.80665  #重力加速度[m/s^2]
    foundation_hight: 0.52049  #射出機構の地面からの高さ[m]
    velocity_lim_max: 15.0 #最大初速度[m/s]
    injection_angle: 48.0 #射出角度[deg]
    yow_limit_m0: [-60.0,60.0] #左の射出機構の方向角の最小最大[deg]
    yow_limit_m1: [-60.0,60.0] #右の射出機構の方向角の最小最大[deg]

injection_interface_node:
  ros__parameters:
    tf_injection2robot_m0: [0.1807, 0.2564] #ロボット->射出機構0のTF[x,y]
    tf_injection2robot_m1: [0.1807, -0.2564] #ロボット->射出機構1のTF[x,y]

RANSAC_localization:
  ros__parameters:
    robot_type: "ER"
    plot_mode: false
    laser_weight: 1.0 #lidarの重み
    odom_weight_liner: 1.0e-1
    odom_weight_angler: 1.0e-1
    voxel_size: 0.05
    trial_num: 40
    inlier_dist_threshold: 0.01
    inlier_length_threshold: 1.3
    initial_pose: [-5.45, 0.3, 0.0]  #初期位置[x,y,yaw]
    tf_laser2robot: [0.4655,0.0,0.0,  3.14159,0.0,0.0]  #ロボット->lidarのTF[x,y,z,r,p,y]
